// import AppFooter from "@/components/app-footer";
// import AppHeader from "@/components/app-header";
// import BackgroundPattern from "@/components/background-pattern";
// import { Toaster } from "@/components/ui/sonner";
// import PetContextProvider from "@/contexts/pet-context-provider";
// import SearchContextProvider from "@/contexts/search-context-provider";
// import { checkAuth, getPetsByUserId } from "@/lib/server-utils";

// export default async function Layout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const session = await checkAuth();
//   const pets = await getPetsByUserId(session.user.id);

//   return (
//     <>
//       <BackgroundPattern />

//       <div className="flex flex-col max-w-[1050px] mx-auto px-4 min-h-screen">
//         <AppHeader />

//         <SearchContextProvider>
//           <PetContextProvider data={pets}>{children}</PetContextProvider>
//         </SearchContextProvider>

//         <AppFooter />
//       </div>

//       <Toaster position="top-right" />
//     </>
//   );
// }

// import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideMenu from "@/components/side-menu";
import AppHeader from "@/components/app-header";
import { checkAuth, getPetsByUserId } from "@/lib/server-utils";
import SearchContextProvider from "@/contexts/search-context-provider";
import PetContextProvider from "@/contexts/pet-context-provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await checkAuth();
  const pets = await getPetsByUserId(session.user.id);

  return (
    <div className={inter.className}>
      <AppHeader />
      <div className="flex">
        <SideMenu />

        <div className="w-full px-4 pt-8">
          <SearchContextProvider>
            <PetContextProvider data={pets}>{children}</PetContextProvider>
          </SearchContextProvider>
        </div>
      </div>
      <Toaster position="top-right" />
    </div>
  );
}
